apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.17.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 5m