apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: network-tools
spec:
  interval: 10m
  timeout: 5m
  values:
    operatorConfig:
      defaultTags:
        - "${tailscaleTag}"
      hostname: "${tailscaleHostname}"
  chart:
    spec:
      chart: tailscale-operator
      version: 1.82.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 5m
  releaseName: tailscale-operator