apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  tailscaleTag: "tag:k8s-operator"
  tailscalePrefix: ""
  tailscaleHostname: "tailscale-operator"
  tailscaleNetName: "taile07e4.ts.net"
