apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./7-ingress
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s