apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-policies
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./1-network-policies
  prune: true
  dependsOn:
    - name: bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s