apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./5-system
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: mysql
      namespace: fleetdm
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis-redis-cluster
      namespace: fleetdm
  dependsOn:
    - name: config
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s