apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ../e2e/4-config
  prune: true
  dependsOn:
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s