apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    tailscale.com/tag: "grafana"
spec:
  defaultBackend:
    service:
      name: grafana
      port:
        name: service
  ingressClassName: tailscale
  tls:
    - hosts:
        - "${tailscalePrefix}grafana"