apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook
  namespace: flux-system
  annotations:
    tailscale.com/tags: tag:webhook
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: webhook-receiver
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - "${tailscalePrefix}webhook-internal-tools"
