apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mysql
  namespace: fleetdm
spec:
  interval: 1m10s
  url: oci://registry-1.docker.io/bitnamicharts/mysql
  ref:
    tag: 12.3.4